"""added content_type

Revision ID: 3136eb729f12
Revises: 7974e5186d7f
Create Date: 2026-02-26 05:41:39.511621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3136eb729f12'
down_revision = '7974e5186d7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_section', schema=None) as batch_op:
        batch_op.drop_column('content_type')

    # ### end Alembic commands ###
