"""empty message

Revision ID: 8242ce61cdf6
Revises: 232c963c748a
Create Date: 2026-02-25 21:31:46.594774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8242ce61cdf6'
down_revision = '232c963c748a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_path', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_path')

    # ### end Alembic commands ###
